/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GameBoard {
        /**
          * @default []
         */
        "activeEffects": any;
        /**
          * @default 8
         */
        "cols": number;
        /**
          * @default false
         */
        "disabled": boolean;
        "forceRefresh": () => Promise<void>;
        /**
          * @default []
         */
        "gridData": any;
        /**
          * @default false
         */
        "isFever": boolean;
        /**
          * @default 'idle'
         */
        "phase": string;
        /**
          * @default 8
         */
        "rows": number;
        /**
          * @default -1
         */
        "selectedCol": number;
        /**
          * @default -1
         */
        "selectedRow": number;
        /**
          * @default false
         */
        "showFps": boolean;
        /**
          * @default null
         */
        "swapAnimation": any;
    }
    interface GameModal {
        /**
          * @default false
         */
        "isOpen": boolean;
    }
    interface GameScore {
        /**
          * @default 25
         */
        "maxMoves": number;
        /**
          * @default 25
         */
        "moves": number;
        /**
          * @default 0
         */
        "score": number;
        /**
          * @default 10000
         */
        "target": number;
    }
    interface GameTile {
        /**
          * @default 0
         */
        "col": number;
        /**
          * @default false
         */
        "falling": boolean;
        /**
          * @default false
         */
        "matched": boolean;
        /**
          * @default 'none'
         */
        "obstacle": string;
        /**
          * @default 0
         */
        "row": number;
        /**
          * @default false
         */
        "selected": boolean;
        /**
          * @default 'none'
         */
        "special": string;
        /**
          * @default 'ruby'
         */
        "type": string;
    }
    interface LevelCard {
        /**
          * @default 0
         */
        "bestScore": number;
        /**
          * @default 'easy'
         */
        "difficulty": string;
        /**
          * @default 1
         */
        "level": number;
        /**
          * @default ''
         */
        "levelTitle": string;
        /**
          * @default false
         */
        "locked": boolean;
        /**
          * @default 0
         */
        "stars": number;
    }
    interface LifeCounter {
        /**
          * @default 5
         */
        "lives": number;
        /**
          * @default 5
         */
        "maxLives": number;
        /**
          * @default ''
         */
        "nextLifeTime": string;
    }
}
export interface GameBoardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGameBoardElement;
}
export interface GameModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGameModalElement;
}
export interface GameTileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGameTileElement;
}
export interface LevelCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLevelCardElement;
}
export interface LifeCounterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLifeCounterElement;
}
declare global {
    interface HTMLGameBoardElementEventMap {
        "tile-swapped": {
    from: { row: number; col: number };
    to: { row: number; col: number };
  };
        "game-tile-selected": {
    row: number;
    col: number;
  };
    }
    interface HTMLGameBoardElement extends Components.GameBoard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGameBoardElementEventMap>(type: K, listener: (this: HTMLGameBoardElement, ev: GameBoardCustomEvent<HTMLGameBoardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGameBoardElementEventMap>(type: K, listener: (this: HTMLGameBoardElement, ev: GameBoardCustomEvent<HTMLGameBoardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGameBoardElement: {
        prototype: HTMLGameBoardElement;
        new (): HTMLGameBoardElement;
    };
    interface HTMLGameModalElementEventMap {
        "modal-closed": void;
    }
    interface HTMLGameModalElement extends Components.GameModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGameModalElementEventMap>(type: K, listener: (this: HTMLGameModalElement, ev: GameModalCustomEvent<HTMLGameModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGameModalElementEventMap>(type: K, listener: (this: HTMLGameModalElement, ev: GameModalCustomEvent<HTMLGameModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGameModalElement: {
        prototype: HTMLGameModalElement;
        new (): HTMLGameModalElement;
    };
    interface HTMLGameScoreElement extends Components.GameScore, HTMLStencilElement {
    }
    var HTMLGameScoreElement: {
        prototype: HTMLGameScoreElement;
        new (): HTMLGameScoreElement;
    };
    interface HTMLGameTileElementEventMap {
        "game-tile-selected": { row: number; col: number };
    }
    interface HTMLGameTileElement extends Components.GameTile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGameTileElementEventMap>(type: K, listener: (this: HTMLGameTileElement, ev: GameTileCustomEvent<HTMLGameTileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGameTileElementEventMap>(type: K, listener: (this: HTMLGameTileElement, ev: GameTileCustomEvent<HTMLGameTileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGameTileElement: {
        prototype: HTMLGameTileElement;
        new (): HTMLGameTileElement;
    };
    interface HTMLLevelCardElementEventMap {
        "level-selected": number;
    }
    interface HTMLLevelCardElement extends Components.LevelCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLevelCardElementEventMap>(type: K, listener: (this: HTMLLevelCardElement, ev: LevelCardCustomEvent<HTMLLevelCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLevelCardElementEventMap>(type: K, listener: (this: HTMLLevelCardElement, ev: LevelCardCustomEvent<HTMLLevelCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLevelCardElement: {
        prototype: HTMLLevelCardElement;
        new (): HTMLLevelCardElement;
    };
    interface HTMLLifeCounterElementEventMap {
        "restore-life-requested": void;
    }
    interface HTMLLifeCounterElement extends Components.LifeCounter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLifeCounterElementEventMap>(type: K, listener: (this: HTMLLifeCounterElement, ev: LifeCounterCustomEvent<HTMLLifeCounterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLifeCounterElementEventMap>(type: K, listener: (this: HTMLLifeCounterElement, ev: LifeCounterCustomEvent<HTMLLifeCounterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLifeCounterElement: {
        prototype: HTMLLifeCounterElement;
        new (): HTMLLifeCounterElement;
    };
    interface HTMLElementTagNameMap {
        "game-board": HTMLGameBoardElement;
        "game-modal": HTMLGameModalElement;
        "game-score": HTMLGameScoreElement;
        "game-tile": HTMLGameTileElement;
        "level-card": HTMLLevelCardElement;
        "life-counter": HTMLLifeCounterElement;
    }
}
declare namespace LocalJSX {
    interface GameBoard {
        /**
          * @default []
         */
        "activeEffects"?: any;
        /**
          * @default 8
         */
        "cols"?: number;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default []
         */
        "gridData"?: any;
        /**
          * @default false
         */
        "isFever"?: boolean;
        "onGame-tile-selected"?: (event: GameBoardCustomEvent<{
    row: number;
    col: number;
  }>) => void;
        "onTile-swapped"?: (event: GameBoardCustomEvent<{
    from: { row: number; col: number };
    to: { row: number; col: number };
  }>) => void;
        /**
          * @default 'idle'
         */
        "phase"?: string;
        /**
          * @default 8
         */
        "rows"?: number;
        /**
          * @default -1
         */
        "selectedCol"?: number;
        /**
          * @default -1
         */
        "selectedRow"?: number;
        /**
          * @default false
         */
        "showFps"?: boolean;
        /**
          * @default null
         */
        "swapAnimation"?: any;
    }
    interface GameModal {
        /**
          * @default false
         */
        "isOpen"?: boolean;
        "onModal-closed"?: (event: GameModalCustomEvent<void>) => void;
    }
    interface GameScore {
        /**
          * @default 25
         */
        "maxMoves"?: number;
        /**
          * @default 25
         */
        "moves"?: number;
        /**
          * @default 0
         */
        "score"?: number;
        /**
          * @default 10000
         */
        "target"?: number;
    }
    interface GameTile {
        /**
          * @default 0
         */
        "col"?: number;
        /**
          * @default false
         */
        "falling"?: boolean;
        /**
          * @default false
         */
        "matched"?: boolean;
        /**
          * @default 'none'
         */
        "obstacle"?: string;
        "onGame-tile-selected"?: (event: GameTileCustomEvent<{ row: number; col: number }>) => void;
        /**
          * @default 0
         */
        "row"?: number;
        /**
          * @default false
         */
        "selected"?: boolean;
        /**
          * @default 'none'
         */
        "special"?: string;
        /**
          * @default 'ruby'
         */
        "type"?: string;
    }
    interface LevelCard {
        /**
          * @default 0
         */
        "bestScore"?: number;
        /**
          * @default 'easy'
         */
        "difficulty"?: string;
        /**
          * @default 1
         */
        "level"?: number;
        /**
          * @default ''
         */
        "levelTitle"?: string;
        /**
          * @default false
         */
        "locked"?: boolean;
        "onLevel-selected"?: (event: LevelCardCustomEvent<number>) => void;
        /**
          * @default 0
         */
        "stars"?: number;
    }
    interface LifeCounter {
        /**
          * @default 5
         */
        "lives"?: number;
        /**
          * @default 5
         */
        "maxLives"?: number;
        /**
          * @default ''
         */
        "nextLifeTime"?: string;
        "onRestore-life-requested"?: (event: LifeCounterCustomEvent<void>) => void;
    }

    interface GameBoardAttributes {
        "gridData": string;
        "rows": number;
        "cols": number;
        "selectedRow": number;
        "selectedCol": number;
        "disabled": boolean;
        "phase": string;
        "swapAnimation": string;
        "activeEffects": string;
        "isFever": boolean;
        "showFps": boolean;
    }
    interface GameModalAttributes {
        "isOpen": boolean;
    }
    interface GameScoreAttributes {
        "score": number;
        "target": number;
        "moves": number;
        "maxMoves": number;
    }
    interface GameTileAttributes {
        "type": string;
        "selected": boolean;
        "special": string;
        "obstacle": string;
        "row": number;
        "col": number;
        "matched": boolean;
        "falling": boolean;
    }
    interface LevelCardAttributes {
        "level": number;
        "stars": number;
        "bestScore": number;
        "locked": boolean;
        "difficulty": string;
        "levelTitle": string;
    }
    interface LifeCounterAttributes {
        "lives": number;
        "maxLives": number;
        "nextLifeTime": string;
    }

    interface IntrinsicElements {
        "game-board": Omit<GameBoard, keyof GameBoardAttributes> & { [K in keyof GameBoard & keyof GameBoardAttributes]?: GameBoard[K] } & { [K in keyof GameBoard & keyof GameBoardAttributes as `attr:${K}`]?: GameBoardAttributes[K] } & { [K in keyof GameBoard & keyof GameBoardAttributes as `prop:${K}`]?: GameBoard[K] };
        "game-modal": Omit<GameModal, keyof GameModalAttributes> & { [K in keyof GameModal & keyof GameModalAttributes]?: GameModal[K] } & { [K in keyof GameModal & keyof GameModalAttributes as `attr:${K}`]?: GameModalAttributes[K] } & { [K in keyof GameModal & keyof GameModalAttributes as `prop:${K}`]?: GameModal[K] };
        "game-score": Omit<GameScore, keyof GameScoreAttributes> & { [K in keyof GameScore & keyof GameScoreAttributes]?: GameScore[K] } & { [K in keyof GameScore & keyof GameScoreAttributes as `attr:${K}`]?: GameScoreAttributes[K] } & { [K in keyof GameScore & keyof GameScoreAttributes as `prop:${K}`]?: GameScore[K] };
        "game-tile": Omit<GameTile, keyof GameTileAttributes> & { [K in keyof GameTile & keyof GameTileAttributes]?: GameTile[K] } & { [K in keyof GameTile & keyof GameTileAttributes as `attr:${K}`]?: GameTileAttributes[K] } & { [K in keyof GameTile & keyof GameTileAttributes as `prop:${K}`]?: GameTile[K] };
        "level-card": Omit<LevelCard, keyof LevelCardAttributes> & { [K in keyof LevelCard & keyof LevelCardAttributes]?: LevelCard[K] } & { [K in keyof LevelCard & keyof LevelCardAttributes as `attr:${K}`]?: LevelCardAttributes[K] } & { [K in keyof LevelCard & keyof LevelCardAttributes as `prop:${K}`]?: LevelCard[K] };
        "life-counter": Omit<LifeCounter, keyof LifeCounterAttributes> & { [K in keyof LifeCounter & keyof LifeCounterAttributes]?: LifeCounter[K] } & { [K in keyof LifeCounter & keyof LifeCounterAttributes as `attr:${K}`]?: LifeCounterAttributes[K] } & { [K in keyof LifeCounter & keyof LifeCounterAttributes as `prop:${K}`]?: LifeCounter[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "game-board": LocalJSX.IntrinsicElements["game-board"] & JSXBase.HTMLAttributes<HTMLGameBoardElement>;
            "game-modal": LocalJSX.IntrinsicElements["game-modal"] & JSXBase.HTMLAttributes<HTMLGameModalElement>;
            "game-score": LocalJSX.IntrinsicElements["game-score"] & JSXBase.HTMLAttributes<HTMLGameScoreElement>;
            "game-tile": LocalJSX.IntrinsicElements["game-tile"] & JSXBase.HTMLAttributes<HTMLGameTileElement>;
            "level-card": LocalJSX.IntrinsicElements["level-card"] & JSXBase.HTMLAttributes<HTMLLevelCardElement>;
            "life-counter": LocalJSX.IntrinsicElements["life-counter"] & JSXBase.HTMLAttributes<HTMLLifeCounterElement>;
        }
    }
}
